name: creative_project_client
description: Creative Project Client
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  process_utils:
    path: "../process_utils"

  api:
    path: "../api"

  window_manager: any
  fluent_ui: any
  system_theme: any
  provider: any
  go_router: any
  http: any
  hive: any
  hive_flutter: any
  file_selector: any
  path_provider: any
  path: ^1.8.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true